core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    # accounts/create/ or accounts/edit/ or accounts/get/?username=user
    path('accounts/<str:action>/', views.account_action, name='account-action'),

    # login/
    path('login/', views.login, name='login'),

    # profile/create/
    path('profile/create/', views.profile_create, name='profile-create'),

    # profile/edit/1/
    path('profile/edit/<int:profile_pk>/', views.profile_edit, name='profile-edit'),

    # profile/delete/1/
    path('profile/delete/<int:profile_pk>/', views.profile_delete, name='profile-delete'),
]

staff/urls.py
from django.urls import path

from . import views


app_name = 'staff'

urlpatterns = [
    # /
    path('', views.StaffHome.as_view(), name='home'),

    # /add_user_to_staff/
    path('manage-staff-user/', views.AddAdminUsers.as_view(), name='add-users'),

    # staff-roles/
    path('staff-roles/', views.StaffRolesView.as_view(), name='staff-view'),

    # staff-groups/
    path('staff-groups/', views.GroupInfoView.as_view(), name='staff-groups'),

    # help/
    path('help/', views.StaffHelpList.as_view(), name='help-list'),

    # help/article/how-to-use-staff-page/
    path('help/article/<int:article_pk>/', views.StaffHelpArticlePage.as_view(), name='help-article'),

    # help/manage/
    path('help/manage/', views.StaffArticleAdd.as_view(), name='help-add'),

    # help/manage/edit/43/
    path('help/manage/edit/<int:article_pk>/', views.StaffArticleEdit.as_view(), name='help-edit'),

    # help/manage/delete/43/
    path('help/manage/delete/<int:article_pk>/', views.StaffArticleHelpDelete.as_view(), name='help-delete'),

    # logs/
    path('staff-activity/', views.StaffLogs.as_view(), name='logs'),

    # search-artists/
    path('search-artists/', views.artists_names, name='search-artists'),

    # manage-albums/
    path('manage-albums/', views.StaffAlbumView.as_view(), name='manage-albums'),

    # manage-albums/published-status/23/
    path('manage-albums/published-status/<int:album_pk>/', views.PublishAlbums.as_view(), name='album-publish-status'),

    # manage-albums/edit/23/
    path('manage-albums/edit/<int:album_pk>/', views.AlbumEditView.as_view(), name='album-edit'),

    # manage-albums/delete/23/
    path('manage-albums/delete/<int:album_pk>/', views.AlbumDelete.as_view(), name='album-delete'),

    # manage-albums/create/
    path('manage-albums/create/', views.StaffAlbumCreateView.as_view(), name='album-create'),

    # manage-albums/disc/new/23/
    path('manage-albums/disc/new/<int:album_id>/', views.add_disc_to_album, name='new-disc'),

    # manage-albums/disc/change/34/
    path('manage-albums/disc/change/<int:disc_id>/', views.change_disc_name, name='change-disc'),

    # manage-albums/disc/delete/34/
    path('manage-albums/disc/delete/<int:disc_id>/', views.delete_disc_from_album, name='delete-disc'),

    # manage-albums/disc/34/song/new/
    path('manage-albums/disc/<int:disc_id>/song/new/', views.CreateSongView.as_view(), name='new-song'),

    # manage-albums/song/14/edit/
    path('manage-albums/song/<int:song_id>/edit/', views.EditSongView.as_view(), name='edit-song'),

    # manage-albums/song/14/delete/
    path('manage-albums/song/<int:song_id>/delete/', views.DeleteSongView.as_view(), name='delete-song'),

    # manage-artists/
    path('manage-artists/', views.StaffArtistsView.as_view(), name='manage-artists'),

    # manage-artists/edit/49/members/
    path('manage-artists/edit/<int:artist_id>/members/', views.EditArtistGroupMember.as_view(), name='group-members'),

    # manage-artists/edit/49/
    path('manage-artists/edit/<int:artist_id>/', views.EditArtist.as_view(), name='artist-edit'),

    # manage-artists/create/
    path('manage-artists/create/', views.ArtistCreate.as_view(), name='artist-create'),

    # manage-artists/delete/23/
    path('manage-artists/delete/<int:artist_id>/', views.ArtistDelete.as_view(), name='artist-delete'),

    # manage-creators/
    path('manage-creators/', views.CreatorsHomeView.as_view(), name='manage-creators'),

    # manage-creators/creator/22/
    path('manage-creators/creator/<int:creator_id>/', views.CreatorDetailView.as_view(), name='creator-detail'),

    # manage-creators/creator/22/edit-genres*/
    path(
        'manage-creators/creator/<int:creator_id>/<str:action>/',
        views.CreatorDetailActions.as_view(),
        name='creator-actions'
    ),

    # manage-creators/creator/delete/22/
    path('manage-creators/creator/delete/<int:creator_id>/', views.CreatorDeleteView.as_view(), name='creator-delete'),

    # manage-creators/creator/edit/22/
    path('manage-creators/creator/edit/<int:creator_id>/', views.CreatorUpdateView.as_view(), name='creator-edit'),

    # manage-creators/creator/new/
    path('manage-creators/create/', views.CreatorNewView.as_view(), name='creator-create'),

]

tyne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls

from core.views import master_login, master_logout, TempHomePage, master_signup

docs_description = """
    This are the API end points available on tyne music
"""

urlpatterns = [
    # /
    path('', TempHomePage.as_view(), name='home'),

    # admin/
    path('admin/', admin.site.urls),

    # core/
    path('core/', include('core.urls')),

    # music/
    path('music/', include('music.urls')),

    # staff/
    path('staff/', include('staff.urls')),

    # login/
    path('login/', master_login, name='master-login'),

    # logout/
    path('logout/', master_logout, name='master-logout'),

    # signup/
    path('signup/', master_signup, name='master-signup'),

    # docs/
    path('docs/', include_docs_urls(title='Tyne Music API docs', description=docs_description))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as __
from django.core.exceptions import ValidationError
from django.conf import settings
from rest_framework.authtoken.models import Token


SINGLE = 'Single'
FAMILY = 'Family'

TIERS = (
    ('S', SINGLE),
    ('F', FAMILY)
)


class User(AbstractUser):
    email = models.EmailField(blank=False, null=False, unique=True)
    tier = models.CharField(max_length=2, choices=TIERS, default='S')

    def clean(self):
        if not self.email:
            raise ValidationError(__('Email field required'))

        if not self.pk and User.objects.filter(email=self.email).count() > 0:
            raise ValidationError(__('User with this Email already exists'))

        return super().clean()

    @property
    def c_tier(self):
        if self.tier == 'S':
            return SINGLE
        elif self.tier == 'F':
            return FAMILY

    @property
    def main_profile(self):
        all_profiles = self.profile_set.order_by('pk')
        main_profiles = [profile for profile in all_profiles if profile.main]

        if len(main_profiles) == 0:
            return None

        else:
            return main_profiles[0]

    @property
    def profile_count(self):
        return self.profile_set.count()

    @property
    def profile_full(self):
        max_ = 1 if self.tier == 'S' else 6
        return self.profile_count >= max_

    def get_user_auth_token(self):
        token = None
        if self.pk:
            tokens = Token.objects.filter(user=self.pk)

            if tokens.count() == 1:
                token = tokens[0]
            elif tokens.count() == 0:
                user = User.objects.get(pk=self.pk)
                token = Token.objects.create(user=user)

        return token

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

        # create a profile for the first time
        if not self.main_profile:
            profile = Profile(
                user=self,
                name=self.username,
                main=True,
            )
            profile.save()

        return self


def upload_avi(instance: 'Profile', filename: str):
    return f'dy/accounts/{instance.user.pk}/{instance.pk}/{filename}'


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    main = models.BooleanField(default=False)
    minor = models.BooleanField(default=False)
    avi = models.ImageField(upload_to=upload_avi, default='/defaults/default_profile.jpg')
    objects = models.Manager()

    @property
    def tier(self):
        if self.user.tier == 'S':
            return SINGLE
        elif self.user.tier == 'F':
            return FAMILY

    @property
    def email(self):
        return self.user.email

    def delete(self, *args, **kwargs):
        if self.main:
            raise ValidationError(__('Main profile cannot be deleted'))

        return super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.clean()
        return super().save()

    def clean(self):
        profile_count = self.user.profile_set.count()

        if not self.pk and self.user.tier == 'S' and profile_count > 0:
                raise ValidationError(__('Maximum possible profiles (Upgradable)'))

        if not self.pk and self.user.main_profile and self.main:
            raise ValidationError(__('A main profile already exists'))

        elif not self.pk and self.user.tier == 'F' and profile_count > 5:
            raise ValidationError(__('Maximum possible profiles'))

        return super().clean()

    def __str__(self):
        return f'{self.name}(profile from {self.user.email})'

staff/models.py
from django.db import models
from django.utils.text import slugify


class HelpArticle(models.Model):
    title = models.CharField(max_length=1000)
    slug = models.SlugField(blank=True, null=True)
    description = models.CharField(max_length=2000)
    help_text = models.TextField()
    is_staff = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return f'HelpArticle: {self.title}'

    def save(self, *args, **kwargs):
        pk = self.pk
        super().save()

        if not pk or not self.slug:
            self.slug = f'{slugify(self.title)}-{self.pk}'
            self.save()

staff/forms.py
from typing import Union, List

from django.utils import timezone
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as __

from .models import HelpArticle
from .widgets import MarkdownEditor
from .logs_processing import log_action_ids, staff_logs, Log


def get_action_choices():
    choices = [(
        val,
        val.translate(str.maketrans('_', ' ')).capitalize()
    ) for val in log_action_ids.__dict__.values()]
    choices.insert(0, ('', '-Select action-'))
    return tuple(choices)


class HelpArticleForm(forms.ModelForm):

    class Meta:
        model = HelpArticle
        exclude = ('slug',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'help_text': MarkdownEditor()
        }


class HelpArticleEditForm(forms.ModelForm):

    class Meta:
        model = HelpArticle
        fields = ('description', 'help_text')
        widgets = {
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'help_text': MarkdownEditor()
        }


class LogSearchForm(forms.Form):
    to = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Action happened to?'}),
        help_text='The user the action happened to',
        required=False
    )
    by = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Action was done by?'}),
        help_text='The user that did the action',
        required=False
    )
    user = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Action happened to or was by whom?'}),
        help_text='Logs that involve the user, This ignores by and to/includes both',
        required=False
    )
    action = forms.ChoiceField(
        choices=get_action_choices(),
        help_text='Action performed; Choose one',
        required=False,
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    start_time = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget(
        attrs={'class': 'form-control'},
        date_format='dd/mm/yyyy',
        time_format='hh:mm',
        date_attrs={
            'type': 'date',
        },
        time_attrs={
            'type': 'time',
        }
    ), required=False, help_text='Filter logs from when')
    end_time = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget(
        date_format='dd/mm/yyyy',
        time_format='hh:mm',
        date_attrs={
            'type': 'date',
        },
        time_attrs={
            'type': 'time',
        }
    ), required=False, help_text='Filter logs up to')

    def clean_end_time(self):
        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')

        if type(start_time) == timezone.datetime and type(end_time) == timezone.datetime:
            if start_time > end_time:
                raise ValidationError(__('Start time cannot be more recent compared to end time.'))

        return end_time

    def get_logs(self) -> Union[List[Log], List]:
        logs = []
        if self.cleaned_data and type(self.cleaned_data) == dict:
            s_data = {
                key: value for key, value in zip(self.cleaned_data.keys(), self.cleaned_data.values()) if value
            }
            logs = staff_logs.search(**s_data)
        return logs

staff/templates/staff/creators/confirm_delete.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block title %}Delete {{ creator.name }}{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static 'staff/css/creators/creator_detail.css' %}" type="text/css">
{% endblock style %}

{% block staff %}active{% endblock staff %}

{% block content %}

    <div class="container text-center">
        <h2>Are you sure you want to delete "{{ creator.name }}"?</h2>

            <div class="alert alert-info">
                Deleting may/will cause loss of all sections and playlists owned by {{ creator.name }}
                <br>Sections - {{ creator.creatorsection_set.count }} <br>Playlists - {{ creator.playlist_set.count }}
            </div>

            <form method="post">
                {% csrf_token %}
                <input type="submit" value="delete" class="btn btn-outline-danger col-sm-4">
                <a href="{% url 'staff:creator-detail' creator_id=creator.pk %}" class="btn btn-outline-dark col-sm-4">cancel</a>
            </form>
    </div>

{% endblock content %}

staff/templates/staff/creators/creator_add.html
{% extends 'staff/staff_base.html' %}

{% load static %}

{% block title %}New creator{% endblock %}

{% block staff %}active{% endblock %}

{% block style %}
<link type="text/css" rel="stylesheet" href="{% static 'staff/css/creators/creator_fr.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <h2>New creator</h2>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'staff/creators/x_creator_form.html' %}
            <hr>
            <div class="form-group">
                <input type="submit" value="save changes" class="btn btn-outline-dark">
                <a href="{% url 'staff:manage-creators' %}" class="btn btn-outline-dark">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block bottomScript %}
    <script src="{% static 'staff/js/aspectRatioCheck.js' %}"></script>
{% endblock %}

staff/templates/staff/creators/creator_detail.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block title %}Manage {{ creator.name }}{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static 'staff/css/creators/creator_detail.css' %}" type="text/css">
{% endblock style %}

{% block staff %}active{% endblock staff %}

{% block content %}


    <div>
        <div class="top-dock row" style="background-image: url('{{ creator.cover.url }}');">
            <div class="col-md-3 text-center">
                <img id="avi" src="{{ creator.avi.url }}" alt="">
            </div>

            <div class="col-md-5">
                <h1 class="bottom-tier">{{ creator.name }}</h1>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h2>Description</h2>
                    {% if creator.description %}
                        <pre class="desc notes alert alert-info">{{ creator.description}}</pre>
                    {% else %}
                        <p>No description available</p>
                    {% endif %}
                </div>

                <div class="col-md-4 dumb-dore">
                    <h2>Genres</h2>
                    <ul class="list-unstyled">
                        {% for genre in creator.genres.all %}
                            <ul>{{ genre.title }}</ul>
                        {% empty %}
                            <span>No Genres yet</span>
                        {% endfor %}
                    </ul>
                    {% if perms.music.change_creator %}
                        <a href="{% url 'staff:creator-actions' creator_id=creator.pk action='edgr' %}" class="btn btn-outline-dark">Edit genres on {{ creator.name }}</a>
                    {% endif %}
                </div>

                <div class="col-md-4">
                    <h2>Curators on {{ creator.name }}</h2>

                    <ul class="list-unstyled">
                        {% for c_user in creator.users.all %}
                            <li class="row c_user">
                                {% if perms.core.view_user %}
                                    <a href="{% url 'staff:staff-view' %}?staff-id={{ c_user.pk }}" class="col-sm-10 overflow-hidden">{{ c_user.username }} ({{ c_user.email }}) {% if user.pk == c_user.pk %}<i>(You)</i>{% endif %}</a>
                                {% else %}
                                    <span class="col-sm-10 overflow-hidden">{{ c_user.username }} ({{ c_user.email }}) {% if user.pk == c_user.pk %}<i>(You)</i>{% endif %}</span>
                                {% endif %}
                                {% if perms.music.change_creator and perms.core.view_user %}
                                    <form method="post" class="col-sm-2" action="{% url 'staff:creator-actions' creator_id=creator.pk action='rmcrf' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="remove-id" value="{{ c_user.pk }}">
                                        <input type="submit" value="remove" class="btn btn-light">
                                    </form>
                                {% endif %}
                            </li>
                        {% empty %}
                            <div class="text-center alert alert-warning">No curators yet</div>
                        {% endfor %}
                    </ul>
                    
                    {% if perms.music.change_creator and perms.core.view_user %}
                        <a href="{% url 'staff:creator-actions' creator_id=creator.pk action='edcr' %}" class="btn btn-outline-dark">Edit curators</a>
                    {% endif %}
                </div>
            </div>
        </div>

        <hr class="fear-line">


        <div class="container">
            <h2>Options</h2>
            <div class="row">
                {% if perms.music.change_creator and perms.music.delete_creator %}
                    <div class="col-md-3">
                        <a href="{% url 'staff:creator-edit' creator.pk %}" class="btn btn-outline-dark">Edit {{ creator.name }}</a>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <a href="{% url 'staff:creator-delete' creator_id=creator.pk %}" class="btn btn-outline-danger">Delete {{ creator.name }}</a>
                    </div>
                    <div class="col-md-1"></div>
                {% endif %}
                <div class="col-md-3">
                    <a href="{% url 'staff:manage-creators' %}" class="btn btn-outline-primary">Other creators</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

staff/templates/staff/creators/creator_edit.html
{% extends 'staff/staff_base.html' %}

{% load static %}

{% block title %}Edit creator "{{ creator.name }}"{% endblock %}

{% block staff %}active{% endblock %}

{% block style %}
<link type="text/css" rel="stylesheet" href="{% static 'staff/css/creators/creator_fr.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Edit <a class="text-decoration-none" href="{% url 'staff:creator-detail' creator.pk %}">{{ creator.name }}</a></h2>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'staff/creators/x_creator_form.html' %}
            <hr>
            <div class="form-group">
                <input type="submit" value="save changes to {{ creator.name }}" class="btn btn-outline-dark">
                <a href="{% url 'staff:creator-detail' creator.pk %}" class="btn btn-outline-dark">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block bottomScript %}
    <script src="{% static 'staff/js/aspectRatioCheck.js' %}"></script>
{% endblock %}

staff/templates/staff/creators/creator_list.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block title %}Manage creators{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static 'staff/css/creators/creator_list.css' %}" type="text/css">
{% endblock style %}

{% block search_action %}{% url 'staff:manage-creators' %}{% endblock search_action %}

{% block search_placeholder %}creators{% endblock search_placeholder %}

{% block staff %}active{% endblock staff %}


{% block content %}


    <div class="container">
        <h2>Manage creators {% if q %}<small class="x-small">filtered by '{{ q }}' <a href="{% url 'staff:manage-creators' %}" class="btn btn-light">clear</a> </small>{% endif %}</h2>
        <p>These are responsible for the creation of curations and playlists that are maintained by Tyne Music</p>


        <div class="row">

            {% if perms.music.add_creator %}
                <div class="text-center skimmy-border add-homage">
                    <a href="{% url 'staff:creator-create' %}" title="add a new creator">
                        <img src="{% static 'svg/misc/add_alone.svg' %}" alt="">
                        <br>
                        new creator
                    </a>
                </div>
            {% endif %}
            {% for creator in creators %}
                <div class="creator text-center skimmy-border" title="{{ creator.name }}">
                    <div class='max'>
                        <h3>{{ creator.name }}</h3>
                        <p>{% for genre in creator.genres.all %}<span>{% if forloop.counter > 1 %}, {% endif %}{{ genre.title }}</span>{% endfor %}</p>
                    </div>
                    <hr>
                    <a class="btn col-md-12" href="{% url 'staff:creator-detail' creator_id=creator.pk %}">go</a>
                </div>            
            {% endfor %}
        </div>

    </div>


{% endblock content %}

staff/templates/staff/creators/edit_curators.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block staff %}active{% endblock staff %}

{% block title %}Edit curators for {{ creator.name }}{% endblock title %}

{% block style %}<link href="{% static 'staff/css/creators/edit_m.css' %}" type="text/css" rel="stylesheet" />{% endblock style %}


{% block content %}
    <div class="container">
        <h1>Edit curators for {{ creator.name }}</h1>


        <form action="" method="post">
            {% csrf_token %}

            <div class="row">

                <!-- HELP and current curators -->
                <div class="col-md-4">
                    <div class="alert alert-info">
                        Staff that can create playlists and sections on behalf of {{ creator.name }}. They are known as curators.
                    </div>
                    <h3>Current curators</h3>
                    <ul>
                        {% for c in creator.users.all %}
                            <li>{{ c.username }} ({{c.email}})</li>
                        {% empty %}
                            No Curators Yet
                        {% endfor %}
                    </ul>
                    <div class="alert alert-info">
                        <strong>Help</strong><br>
                        Hold down ctrl and click to select or deselect curators <br>
                        Selected curators are highlighted
                    </div>
                    <br>
                    <a href="{% url 'staff:creator-detail' creator_id=creator.pk %}" class="btn btn-outline-dark">view creator '{{ creator.name }}'</a>
                </div>

                <!-- Genre select form -->
                <div class="col-md-4">
                    <h3>Select Curators</h3>
                    <div class="form-group">
                        {{ form.users }}
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="submit" value="save curators" class="btn btn-outline-dark">
                        <input type="reset" value="discard changes" class="btn btn-outline-danger">
                    </div>
                </div>

                <!-- Edited genres -->
                <div class="col-md-4">
                    <div class="alert alert-info">
                        Curators to be saved to '{{ creator.name }}' show up below
                    </div>

                    <ul id="edited-g"></ul>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block bottomScript %}
    <script src="{% static 'staff/js/creators/edit_m.js' %}"></script>
{% endblock bottomScript %}

staff/templates/staff/creators/edit_genres.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block staff %}active{% endblock staff %}

{% block title %}Edit genres for {{ creator.name }}{% endblock title %}

{% block style %}<link href="{% static 'staff/css/creators/edit_m.css' %}" type="text/css" rel="stylesheet" />{% endblock style %}


{% block content %}
    <div class="container">
        <h1>Edit genres for {{ creator.name }}</h1>


        <form action="" method="post">
            {% csrf_token %}

            <div class="row">

                <!-- HELP and current genre -->
                <div class="col-md-4">
                    <div class="alert alert-info">
                        Music on this creator are generally from the following genres.
                    </div>
                    <h3>Current genres</h3>
                    <ul>
                        {% for g in creator.genres.all %}
                            <li>{{ g.title }}</li>
                        {% empty %}
                            No Genres Selected
                        {% endfor %}
                    </ul>
                    <div class="alert alert-info">
                        <strong>Help</strong><br>
                        Hold down ctrl and click to select or deselect genres <br>
                        Selected genres are highlighted
                    </div>
                    <br>
                    <a href="{% url 'staff:creator-detail' creator_id=creator.pk %}" class="btn btn-outline-dark">view creator '{{ creator.name }}'</a>
                </div>

                <!-- Genre select form -->
                <div class="col-md-4">
                    <h3>Select Genres</h3>
                    <div class="form-group">
                        {{ form.genres }}
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="submit" value="save genres" class="btn btn-outline-dark">
                        <input type="reset" value="discard changes" class="btn btn-outline-danger">
                    </div>
                </div>

                <!-- Edited genres -->
                <div class="col-md-4">
                    <div class="alert alert-info">
                        Genres to be saved to '{{ creator.name }}' show up below
                    </div>

                    <ul id="edited-g"></ul>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}


{% block bottomScript %}
    <script src="{% static 'staff/js/creators/edit_m.js' %}"></script>
{% endblock bottomScript %}