core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    # accounts/create/ or accounts/edit/ or accounts/get/?username=user
    path('accounts/<str:action>/', views.account_action, name='account-action'),

    # login/
    path('login/', views.login, name='login'),

    # profile/create/
    path('profile/create/', views.profile_create, name='profile-create'),

    # profile/edit/1/
    path('profile/edit/<int:profile_pk>/', views.profile_edit, name='profile-edit'),

    # profile/delete/1/
    path('profile/delete/<int:profile_pk>/', views.profile_delete, name='profile-delete'),
]

staff/urls.py
from django.urls import path

from . import views


app_name = 'staff'

urlpatterns = [
    # /
    path('', views.StaffHome.as_view(), name='home'),

    # /add_user_to_staff/
    path('manage-staff-user/', views.AddAdminUsers.as_view(), name='add-users'),

    # staff-roles/
    path('staff-roles/', views.StaffRolesView.as_view(), name='staff-view'),

    # staff-groups/
    path('staff-groups/', views.GroupInfoView.as_view(), name='staff-groups'),

    # help/
    path('help/', views.StaffHelpList.as_view(), name='help-list'),

    # help/article/how-to-use-staff-page/
    path('help/article/<int:article_pk>/', views.StaffHelpArticlePage.as_view(), name='help-article'),

    # help/manage/
    path('help/manage/', views.StaffArticleAdd.as_view(), name='help-add'),

    # help/manage/edit/43/
    path('help/manage/edit/<int:article_pk>/', views.StaffArticleEdit.as_view(), name='help-edit'),

    # help/manage/delete/43/
    path('help/manage/delete/<int:article_pk>/', views.StaffArticleHelpDelete.as_view(), name='help-delete'),

    # logs/
    path('staff-activity/', views.StaffLogs.as_view(), name='logs'),

    # search-artists/
    path('search-artists/', views.artists_names, name='search-artists'),

    # manage-albums/
    path('manage-albums/', views.StaffAlbumView.as_view(), name='manage-albums'),

    # manage-albums/published-status/23/
    path('manage-albums/published-status/<int:album_pk>/', views.PublishAlbums.as_view(), name='album-publish-status'),

    # manage-albums/edit/23/
    path('manage-albums/edit/<int:album_pk>/', views.AlbumEditView.as_view(), name='album-edit'),

    # manage-albums/delete/23/
    path('manage-albums/delete/<int:album_pk>/', views.AlbumDelete.as_view(), name='album-delete'),

    # manage-albums/create/
    path('manage-albums/create/', views.StaffAlbumCreateView.as_view(), name='album-create'),

    # manage-albums/disc/new/23/
    path('manage-albums/disc/new/<int:album_id>/', views.add_disc_to_album, name='new-disc'),

    # manage-albums/disc/change/34/
    path('manage-albums/disc/change/<int:disc_id>/', views.change_disc_name, name='change-disc'),

    # manage-albums/disc/delete/34/
    path('manage-albums/disc/delete/<int:disc_id>/', views.delete_disc_from_album, name='delete-disc'),

    # manage-albums/disc/34/song/new/
    path('manage-albums/disc/<int:disc_id>/song/new/', views.CreateSongView.as_view(), name='new-song'),

    # manage-albums/song/14/edit/
    path('manage-albums/song/<int:song_id>/edit/', views.EditSongView.as_view(), name='edit-song'),

    # manage-albums/song/14/delete/
    path('manage-albums/song/<int:song_id>/delete/', views.DeleteSongView.as_view(), name='delete-song'),

    # manage-artists/
    path('manage-artists/', views.StaffArtistsView.as_view(), name='manage-artists'),

    # manage-artists/edit/49/members/
    path('manage-artists/edit/<int:artist_id>/members/', views.EditArtistGroupMember.as_view(), name='group-members'),

    # manage-artists/edit/49/
    path('manage-artists/edit/<int:artist_id>/', views.EditArtist.as_view(), name='artist-edit'),

    # manage-artists/create/
    path('manage-artists/create/', views.ArtistCreate.as_view(), name='artist-create'),

    # manage-artists/delete/23/
    path('manage-artists/delete/<int:artist_id>/', views.ArtistDelete.as_view(), name='artist-delete'),

    # manage-creators/
    path('manage-creators/', views.CreatorsHomeView.as_view(), name='manage-creators'),

    # manage-creators/creator/22/
    path('manage-creators/creator/<int:creator_id>/', views.CreatorDetailView.as_view(), name='creator-detail'),

    # manage-creators/creator/22/edit-genres*/
    path(
        'manage-creators/creator/<int:creator_id>/<str:action>/',
        views.CreatorDetailActions.as_view(),
        name='creator-actions'
    ),

    # manage-creators/creator/delete/22/
    path('manage-creators/creator/delete/<int:creator_id>/', views.CreatorDeleteView.as_view(), name='creator-delete'),

    # manage-creators/creator/edit/22/
    path('manage-creators/creator/edit/<int:creator_id>/', views.CreatorUpdateView.as_view(), name='creator-edit'),

    # manage-creators/creator/new/
    path('manage-creators/create/', views.CreatorNewView.as_view(), name='creator-create'),

]

tyne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls

from core.views import master_login, master_logout, TempHomePage, master_signup

docs_description = """
    This are the API end points available on tyne music
"""

urlpatterns = [
    # /
    path('', TempHomePage.as_view(), name='home'),

    # admin/
    path('admin/', admin.site.urls),

    # core/
    path('core/', include('core.urls')),

    # music/
    path('music/', include('music.urls')),

    # staff/
    path('staff/', include('staff.urls')),

    # login/
    path('login/', master_login, name='master-login'),

    # logout/
    path('logout/', master_logout, name='master-logout'),

    # signup/
    path('signup/', master_signup, name='master-signup'),

    # docs/
    path('docs/', include_docs_urls(title='Tyne Music API docs', description=docs_description))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/models.py
from django.db import models
from django.utils.text import slugify


class HelpArticle(models.Model):
    title = models.CharField(max_length=1000)
    slug = models.SlugField(blank=True, null=True)
    description = models.CharField(max_length=2000)
    help_text = models.TextField()
    is_staff = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return f'HelpArticle: {self.title}'

    def save(self, *args, **kwargs):
        pk = self.pk
        super().save()

        if not pk or not self.slug:
            self.slug = f'{slugify(self.title)}-{self.pk}'
            self.save()

staff/views.py
from typing import List, Set
import logging

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View, generic
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group
from django.http import Http404, JsonResponse
from django.core.exceptions import ObjectDoesNotExist, BadRequest
from django.db.models import Q
from django.contrib.messages import add_message, constants as message_constants

import mutagen

from core.models import User
from music.models import Album, Artist, Disc, Song, Creator
from music.forms import AlbumEditForm, AlbumForm, ArtistEditForm, ArtistForm, SongEditForm, SongForm, \
    CreatorGenreForm, CreatorUsersForm, CreatorForm, CreatorEditForm
from tyne_utils.funcs import is_string_true_or_false, strip_punctuation
from .models import HelpArticle
from .forms import HelpArticleForm, HelpArticleEditForm, LogSearchForm
from .logs_processing import log_action_ids, staff_logs
from .staff_actions import staff_actions, superuser_actions


staff_logger = logging.getLogger('tyne.staff')


def info_log_staff_message(action_id: log_action_ids, message: str):
    staff_logger.info(f'ID: {action_id}:{message}')


@user_passes_test(test_func=lambda user: user.is_staff)
def artists_names(request):
    if request.method == 'GET':
        name = request.GET.get('name', '')
        artists = Artist.objects.filter(name__icontains=name)
        return JsonResponse([[artist.name, artist.pk] for artist in artists], safe=False)


# access mixin for staff, throw 404 if user not staff or superuser denied
class StaffAccessMixin(UserPassesTestMixin):
    def test_func(self):
        if hasattr(self, 'request'):
            return self.request.user.is_staff or self.request.user.is_superuser

    def handle_no_permission(self):
        raise Http404


# superuser access mixin
class SuperuserAccessMixin(StaffAccessMixin):
    # only superusers can access this page
    def test_func(self):
        if hasattr(self, 'request') and hasattr(self.request.user, 'is_superuser'):
            return self.request.user.is_superuser


# permission mixin for staff, throw 404 if permission denied
class StaffPermissionMixin(PermissionRequiredMixin):
    def handle_no_permission(self):
        raise Http404


# see all user available actions
class StaffHome(StaffAccessMixin, generic.TemplateView):
    template_name = 'staff/staff_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_actions = [action for action in staff_actions if self.request.user.has_perms(action.get('permissions', []))]

        if self.request.user.is_superuser:
            all_actions.extend(superuser_actions)

        context.update({
            'staff_actions': all_actions
        })
        return context


# manage a user, give a user permission
class AddAdminUsers(StaffAccessMixin, StaffPermissionMixin, View):
    template = 'staff/add_user.html'
    permission_required = (
        'auth.change_group', 'auth.view_group', 'auth.change_permission', 'auth.view_permission',
        'core.change_user', 'core.view_user'
    )

    def log_message_user(self):
        return f'{self.request.user.username}({self.request.user.pk})'

    def add_user_to_group(self, user: User, group_pk: int) -> bool:
        try:
            group = Group.objects.get(pk=group_pk)
            user.groups.add(group)
            added = True
            user_info = f'{user.username}({user.pk})'
            info_log_staff_message(
                log_action_ids.ADD_TO_GROUP,
                f'{self.log_message_user()}) added {user_info} to {strip_punctuation(group.name)}'
            )
        except ObjectDoesNotExist:
            added = False
        return added

    def remove_user_from_staff(self, user):
        user.groups.clear()
        user.is_staff = False
        user.save()
        user_info = f'{user.username}({user.pk})'
        info_log_staff_message(
            log_action_ids.REMOVE_STAFF,
            f'{self.log_message_user()} removed {user_info} from staff'
        )

    def make_user_staff(self, user):
        user.is_staff = True
        user.save()
        info_log_staff_message(
            log_action_ids.ADD_STAFF,
            f'{self.log_message_user()} made {user.username}({user.pk}) staff'
        )

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        email = request.POST.get('email', '')
        manage = None
        email_not_found = False
        message = None
        user_info = ''

        try:
            manage = User.objects.get(email=email)
            user_info = f'{manage.username}({manage.pk})'
        except ObjectDoesNotExist:
            email_not_found = True

        if email == request.user.email:
            manage = None
            email_not_found = True
            message = 'You have yourself to blame'

        # make staff
        make_staff = request.POST.get('make-staff', '0')
        if is_string_true_or_false(make_staff) and manage and not manage.is_staff:
            self.make_user_staff(manage)
            message = f'Added \'{manage.username}\' to staff'

        # remove from staff
        remove_staff = request.POST.get('remove-staff', '0')
        if is_string_true_or_false(remove_staff) and manage and manage.is_staff:
            self.remove_user_from_staff(manage)
            message = f'Removed \'{manage.username} from staff\''

        # add to group
        add_to_group = request.POST.get('group-add', '')
        if add_to_group and add_to_group.isdigit() and manage:
            add_to_group_result = self.add_user_to_group(group_pk=add_to_group, user=manage)
            if add_to_group_result:
                message = f'\'{manage.username}\' added to group ID {add_to_group}'

        # remove from group
        remove_from_group = request.POST.get('group-remove', '')
        if remove_from_group and remove_from_group.isdigit() and manage:
            manage.groups.remove(remove_from_group)
            message = f'\'{manage.username}\' removed from group ID {remove_from_group}'
            info_log_staff_message(
                log_action_ids.REMOVE_FROM_GROUP,
                f'{self.log_message_user()} removed {user_info} from group({remove_from_group})'
            )

        if message:
            add_message(request, message_constants.SUCCESS, message=message)

        return render(request, self.template, {
            'email': email,
            'manage': manage,
            'email_not_found': email_not_found,
            'groups': Group.objects.all(),
        })


# view help articles listed
class StaffHelpList(StaffAccessMixin, generic.ListView):
    queryset = HelpArticle.objects.filter(is_staff=True).order_by('-id')
    context_object_name = 'articles'
    template_name = 'staff/help_list.html'

    def get_queryset(self):
        q_set = super().get_queryset()
        query = self.request.GET.get('q')
        if query:
            q_set = q_set.filter((Q(title__icontains=query) | Q(description__icontains=query)))
        return q_set


# view a help article
class StaffHelpArticlePage(StaffAccessMixin, generic.DetailView):
    queryset = HelpArticle.objects.all()
    pk_url_kwarg = 'article_pk'
    context_object_name = 'article'
    template_name = 'staff/help_detail.html'


# add a help article
class StaffArticleAdd(StaffAccessMixin, PermissionRequiredMixin, generic.CreateView):
    model = HelpArticle
    form_class = HelpArticleForm
    template_name = 'staff/article_edit.html'
    permission_required = ('staff.add_helparticle',)

    def get_success_url(self):
        user_info = f'{self.request.user.username}({self.request.user.pk})'
        info_log_staff_message(
            log_action_ids.CREATE_ARTICLE,
            f'{user_info} created article {strip_punctuation(self.object.title)}({self.object.pk})'
        )
        return reverse('staff:help-article', kwargs={'article_pk': str(self.object.pk)})


# edit a help article
class StaffArticleEdit(StaffAccessMixin, PermissionRequiredMixin, generic.UpdateView):
    model = HelpArticle
    form_class = HelpArticleEditForm
    template_name = 'staff/article_edit.html'
    pk_url_kwarg = 'article_pk'
    context_object_name = 'article'
    permission_required = ('staff.change_helparticle',)

    def get_success_url(self):
        user_info = f'{self.request.user.username}({self.request.user.pk})'
        info_log_staff_message(
            log_action_ids.EDIT_ARTICLE,
            f'{user_info} edited article {strip_punctuation(self.object.title)}({self.object.pk})'
        )
        return reverse('staff:help-article', kwargs={'article_pk': str(self.object.pk)})


# edit a help article
class StaffArticleHelpDelete(StaffAccessMixin, PermissionRequiredMixin, generic.DeleteView):
    model = HelpArticle
    pk_url_kwarg = 'article_pk'
    context_object_name = 'article'
    permission_required = ('staff.delete_helparticle',)

    def get_success_url(self):
        user_info = f'{self.request.user.username}({self.request.user.pk})'
        info_log_staff_message(
            log_action_ids.DELETE_ARTICLE,
            f'{user_info} deleted article {strip_punctuation(self.object.title)}({self.object.pk})'
        )
        return reverse("staff:help-list")


# view users and their roles
class StaffRolesView(StaffAccessMixin, StaffPermissionMixin, generic.TemplateView):
    template_name = 'staff/staff_roles.html'
    permission_required = (
        'auth.change_group', 'auth.view_group', 'auth.change_permission', 'auth.view_permission',
        'core.change_user', 'core.view_user'
    )

    def get_permission_required(self):
        perms = super().get_permission_required()

staff/templates/staff/artists/artist_delete.html
{% extends 'staff/staff_base.html' %}

{% block title %}Delete {{ artist.name }}{% endblock title %}

{% block staff %}active{% endblock staff %}

{% block content %}

    <div class="container text-center">
        <h2>Are you sure you want to delete "{{ artist.name }}"</h2>

        <div class="alert alert-info">
            The artist and all their info will be deleted/lost and cannot be recovered
        </div>

        <form method="post">
            {% csrf_token %}
            <div class="row">
                <button type="submit" class="btn btn-outline-danger col-md-4">Delete '{{ artist.name }}'</button>
                <div class="col-md-4"></div>
                <a href="{% url 'staff:manage-artists' %}?artist-id={{ artist.pk }}" class="btn btn-outline-dark col-md-4">cancel</a>
            </div>
        </form>
    </div>


{% endblock content %}

staff/templates/staff/artists/create_artist.html
{% extends 'staff/staff_base.html' %}

{% load static %}

{% block title %}Create new artist{% endblock title %}

{% block style %}
    {{ form.media.css }}
{% endblock style %}

{% block staff %}active{% endblock staff %}

{% block content %}

    <div class="container">
        <h2>Create new artist</h2>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% include 'staff/artists/r_artist_form.html' %}

            <hr>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-dark">save new artist</button>
            </div>
        
        </form>



    </div>



{% endblock content %}

{% block bottomScript %}
    {{ form.media.js }}
{% endblock bottomScript %}

staff/templates/staff/artists/edit_artist.html
{% extends 'staff/staff_base.html' %}

{% block title %}Edit {{ artist.name }}(artist){% endblock title %}

{% block style %}
    {{ form.media.css }}
{% endblock style %}

{% block staff %}active{% endblock staff %}

{% block content %}

    <div class="container">
        <h2>Edit "<a href="{% url 'staff:manage-artists' %}?artist-id={{ artist.pk }}">{{ artist.name }}</a>"</h2>
        
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            {% include 'staff/artists/r_artist_form.html' %}
            
            <hr>
            <div class="form-group row">
                <div class="col-md-3">
                    <button class="btn btn-outline-dark" type="submit">save changes to '{{ artist.name }}'</button>
                </div>
                <div class="col-md-3">
                    <a href="{% url 'staff:manage-artists' %}?artist-id={{ artist.pk }}" class="btn btn-outline-primary">cancel</a>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block bottomScript %}
    {{ form.media.js }}
{% endblock bottomScript %}

staff/templates/staff/artists/manage_artists.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block title %}Manage {% if artist_id %}{{ artist.name }}{% else %}Artists{% endif %}{% endblock title %}

{% block style %}
    {% if artist_id %}
        <link rel="stylesheet" href="{% static 'staff/css/artists/single_artist.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'staff/css/select_artists.css' %}" type="text/css">
    {% else %}
        <link rel="stylesheet" href="{% static 'staff/css/artists/artists.css' %}" type="text/css">
    {% endif %}
{% endblock style %}

{% block search_action %}{% url 'staff:manage-artists' %}{% endblock search_action %}

{% block search_placeholder %}artist by name or nicknames{% endblock search_placeholder %}

{% block staff %}active{% endblock staff %}

{% block content %}


    <div class="container">
        {% if artist_id %}
            {% comment %} Single artist {% endcomment %}
            {% include 'staff/artists/single_artist.html' %}
        {% else %}
            {% comment %} Multiple artists {% endcomment %}
            {% include 'staff/artists/multiple_artists.html' %}
        {% endif %}
    </div>
    


{% endblock content %}

{% block bottomScript %}
    <script src="{% static 'js/ajaxWrapper.js' %}"></script>
    <script src="{% static 'staff/js/select_artists.js' %}"></script>
{% endblock bottomScript %}

staff/templates/staff/artists/multiple_artists.html
<div>
    <div class="row top-links">
        <h2 class="col-md-3">
            Manage Artists
            <small>
            {% if artist_type == 'G' %}
                (Groups only)
            {% else %}
                {% if artist_type == 'L' %}
                    (Loner Artists only)
                {% endif %}
            {% endif %}
            </small>
        </h2>
        <div class="col-md-2">
            <a href="{% url 'staff:artist-create' %}" class="btn btn-outline-primary">New Artist</a>
        </div>

        <div class="col-md-2">
            <a href="{% url 'staff:manage-artists' %}?t=G" class="btn btn-{% if artist_type != 'G' %}outline-{% endif %}dark">Groups / Bands</a>
        </div>

        <div class="col-md-2">
            <a href="{% url 'staff:manage-artists' %}?t=L" class="btn btn-{% if artist_type != 'L' %}outline-{% endif %}dark">Loner Artists</a>
        </div>
        
        {% if artist_type or q %}
        <div class="col-md-2">
            <a href="{% url 'staff:manage-artists' %}" class="btn btn-outline-primary">All</a>
        </div>
        {% endif %}
    </div>

    <script type="text/javascript">
        function clickLink(linkId) {
            document.getElementById(linkId).click()
        }
    </script>
    <div class="row">
        {% for artist in artists %}
            <div class="artist col-md-2">
                <div class="artist-info">
                    <h5
                        class="artist-title"
                        data-bs-toggle="tooltip"
                        data-bs-placement="top"
                        data-bs-html="true"
                        title="<img class='tool-img' src='{{ artist.avi.url }}'>"
                    >{{ artist.name }}</h5>
                    <p>
                        {% if artist.is_group %}
                            GROUP with {{ artist.group_members.count }} member(s)
                        {% endif %}
                        
                        {% if artist.nicknames %}
                            {{ artist.nicknames }}
                        {% endif %}
                    </p>
                </div>
                <div class="artist-link" onclick="clickLink('{{ artist.pk }}-link')" aria-label="manage {{ artist.title }}">
                    <a id="{{ artist.pk }}-link" href="{% url 'staff:manage-artists' %}?artist-id={{ artist.pk }}">manage</a>
                </div>
            </div>
        {% empty %}
            
            <div class="alert alert-info text-center text-dark">
                No artists here
            </div>
        {% endfor %}
    </div>


</div>

staff/templates/staff/artists/single_artist.html
<div>
    <div class="row artist-row">
        <div class="main-cover">
            {% if artist.cover %}
                <img src="{{ artist.cover.url }}" alt="artist cover image">
            {% endif %}
        </div>

        <hr>

        <div class="col-md-4">
            <ul class="artist-info">
                <li>
                    <span class="title">Name</span><br>
                    <span class="value">{{ artist.name }}</span>
                </li>
                <hr>
                <li>
                    <span class="title">Nicknames</span><br>
                    <span class="value">
                        {% if artist.nicknames %}
                            <ul>
                                {% for n in artist.all_nicknames %}
                                    <li>{{ n}}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            No nicknames
                        {% endif %}
                    </span>
                </li>
                <hr>
                <li>
                    <span class="title">Type</span><br>
                    <span class="value">{{ artist.a_type }}</span>
                </li>
            </ul>
        </div>
        <div class="col-md-4">
            <h3 class="x-title">Artist Bio</h3>
            {% if artist.bio %}
                <pre class="x-p alert alert-info">{{ artist.bio }}</pre>
            {% else %}
                <p>No bio yet</p>
            {% endif %}
        </div>
        <div class="col-md-4 text-center">
            {% if artist.avi %}
                <img src="{{ artist.avi.url }}" alt="{{ artist.name }}'s avi" class="artist-avi">
            {% endif %}
        </div>
    </div>

    <hr>

    <div>
        <h3 class="text-center x-title">Actions</h3>
        {% if artist.is_group %}
            <form id="group-members-edit" action="{% url 'staff:group-members' artist_id=artist.pk %}" method="post" class="alert alert-info">
                <h4>Add Group members</h4>
                
                {% csrf_token %}
                {% include 'staff/select_artists.html' with c_artists=artist.group_members to='group' modal_title="Group Artists" %}

                <div class="form-group">
                    <br>
                    <button class="btn btn-outline-dark" type="submit">save group members</button>    
                </div>
            </form>
        {% endif %}
        <br>
        <div class="row actions">
            <div class="col-md-4">
                <a href="{% url 'staff:manage-artists' %}" class="btn btn-outline-dark">All artists</a>
            </div>
            <div class="col-md-4">
                <a href="{% url 'staff:artist-edit' artist_id=artist.pk %}" class="btn btn-outline-dark">Edit {{ artist.name }}</a>
            </div>
            <div class="col-md-4">
                <a href="{% url 'staff:artist-delete' artist_id=artist.pk %}" class="btn btn-outline-danger">Delete {{ artist.name }}</a>
            </div>
        </div>
    </div>
    
    
</div>