core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    # accounts/create/ or accounts/edit/ or accounts/get/?username=user
    path('accounts/<str:action>/', views.account_action, name='account-action'),

    # login/
    path('login/', views.login, name='login'),

    # profile/create/
    path('profile/create/', views.profile_create, name='profile-create'),

    # profile/edit/1/
    path('profile/edit/<int:profile_pk>/', views.profile_edit, name='profile-edit'),

    # profile/delete/1/
    path('profile/delete/<int:profile_pk>/', views.profile_delete, name='profile-delete'),
]

staff/urls.py
from django.urls import path

from . import views


app_name = 'staff'

urlpatterns = [
    # /
    path('', views.StaffHome.as_view(), name='home'),

    # /add_user_to_staff/
    path('manage-staff-user/', views.AddAdminUsers.as_view(), name='add-users'),

    # staff-roles/
    path('staff-roles/', views.StaffRolesView.as_view(), name='staff-view'),

    # staff-groups/
    path('staff-groups/', views.GroupInfoView.as_view(), name='staff-groups'),

    # help/
    path('help/', views.StaffHelpList.as_view(), name='help-list'),

    # help/article/how-to-use-staff-page/
    path('help/article/<int:article_pk>/', views.StaffHelpArticlePage.as_view(), name='help-article'),

    # help/manage/
    path('help/manage/', views.StaffArticleAdd.as_view(), name='help-add'),

    # help/manage/edit/43/
    path('help/manage/edit/<int:article_pk>/', views.StaffArticleEdit.as_view(), name='help-edit'),

    # help/manage/delete/43/
    path('help/manage/delete/<int:article_pk>/', views.StaffArticleHelpDelete.as_view(), name='help-delete'),

    # logs/
    path('staff-activity/', views.StaffLogs.as_view(), name='logs'),

    # search-artists/
    path('search-artists/', views.artists_names, name='search-artists'),

    # manage-albums/
    path('manage-albums/', views.StaffAlbumView.as_view(), name='manage-albums'),

    # manage-albums/published-status/23/
    path('manage-albums/published-status/<int:album_pk>/', views.PublishAlbums.as_view(), name='album-publish-status'),

    # manage-albums/edit/23/
    path('manage-albums/edit/<int:album_pk>/', views.AlbumEditView.as_view(), name='album-edit'),

    # manage-albums/delete/23/
    path('manage-albums/delete/<int:album_pk>/', views.AlbumDelete.as_view(), name='album-delete'),

    # manage-albums/create/
    path('manage-albums/create/', views.StaffAlbumCreateView.as_view(), name='album-create'),

    # manage-albums/disc/new/23/
    path('manage-albums/disc/new/<int:album_id>/', views.add_disc_to_album, name='new-disc'),

    # manage-albums/disc/change/34/
    path('manage-albums/disc/change/<int:disc_id>/', views.change_disc_name, name='change-disc'),

    # manage-albums/disc/delete/34/
    path('manage-albums/disc/delete/<int:disc_id>/', views.delete_disc_from_album, name='delete-disc'),

    # manage-albums/disc/34/song/new/
    path('manage-albums/disc/<int:disc_id>/song/new/', views.CreateSongView.as_view(), name='new-song'),

    # manage-albums/song/14/edit/
    path('manage-albums/song/<int:song_id>/edit/', views.EditSongView.as_view(), name='edit-song'),

    # manage-albums/song/14/delete/
    path('manage-albums/song/<int:song_id>/delete/', views.DeleteSongView.as_view(), name='delete-song'),

    # manage-artists/
    path('manage-artists/', views.StaffArtistsView.as_view(), name='manage-artists'),

    # manage-artists/edit/49/members/
    path('manage-artists/edit/<int:artist_id>/members/', views.EditArtistGroupMember.as_view(), name='group-members'),

    # manage-artists/edit/49/
    path('manage-artists/edit/<int:artist_id>/', views.EditArtist.as_view(), name='artist-edit'),

    # manage-artists/create/
    path('manage-artists/create/', views.ArtistCreate.as_view(), name='artist-create'),

    # manage-artists/delete/23/
    path('manage-artists/delete/<int:artist_id>/', views.ArtistDelete.as_view(), name='artist-delete'),

    # manage-creators/
    path('manage-creators/', views.CreatorsHomeView.as_view(), name='manage-creators'),

    # manage-creators/creator/22/
    path('manage-creators/creator/<int:creator_id>/', views.CreatorDetailView.as_view(), name='creator-detail'),

    # manage-creators/creator/22/edit-genres*/
    path(
        'manage-creators/creator/<int:creator_id>/<str:action>/',
        views.CreatorDetailActions.as_view(),
        name='creator-actions'
    ),

    # manage-creators/creator/delete/22/
    path('manage-creators/creator/delete/<int:creator_id>/', views.CreatorDeleteView.as_view(), name='creator-delete'),

    # manage-creators/creator/edit/22/
    path('manage-creators/creator/edit/<int:creator_id>/', views.CreatorUpdateView.as_view(), name='creator-edit'),

    # manage-creators/creator/new/
    path('manage-creators/create/', views.CreatorNewView.as_view(), name='creator-create'),

]

tyne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls

from core.views import master_login, master_logout, TempHomePage, master_signup

docs_description = """
    This are the API end points available on tyne music
"""

urlpatterns = [
    # /
    path('', TempHomePage.as_view(), name='home'),

    # admin/
    path('admin/', admin.site.urls),

    # core/
    path('core/', include('core.urls')),

    # music/
    path('music/', include('music.urls')),

    # staff/
    path('staff/', include('staff.urls')),

    # login/
    path('login/', master_login, name='master-login'),

    # logout/
    path('logout/', master_logout, name='master-logout'),

    # signup/
    path('signup/', master_signup, name='master-signup'),

    # docs/
    path('docs/', include_docs_urls(title='Tyne Music API docs', description=docs_description))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as __
from django.core.exceptions import ValidationError
from django.conf import settings
from rest_framework.authtoken.models import Token


SINGLE = 'Single'
FAMILY = 'Family'

TIERS = (
    ('S', SINGLE),
    ('F', FAMILY)
)


class User(AbstractUser):
    email = models.EmailField(blank=False, null=False, unique=True)
    tier = models.CharField(max_length=2, choices=TIERS, default='S')

    def clean(self):
        if not self.email:
            raise ValidationError(__('Email field required'))

        if not self.pk and User.objects.filter(email=self.email).count() > 0:
            raise ValidationError(__('User with this Email already exists'))

        return super().clean()

    @property
    def c_tier(self):
        if self.tier == 'S':
            return SINGLE
        elif self.tier == 'F':
            return FAMILY

    @property
    def main_profile(self):
        all_profiles = self.profile_set.order_by('pk')
        main_profiles = [profile for profile in all_profiles if profile.main]

        if len(main_profiles) == 0:
            return None

        else:
            return main_profiles[0]

    @property
    def profile_count(self):
        return self.profile_set.count()

    @property
    def profile_full(self):
        max_ = 1 if self.tier == 'S' else 6
        return self.profile_count >= max_

    def get_user_auth_token(self):
        token = None
        if self.pk:
            tokens = Token.objects.filter(user=self.pk)

            if tokens.count() == 1:
                token = tokens[0]
            elif tokens.count() == 0:
                user = User.objects.get(pk=self.pk)
                token = Token.objects.create(user=user)

        return token

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

        # create a profile for the first time
        if not self.main_profile:
            profile = Profile(
                user=self,
                name=self.username,
                main=True,
            )
            profile.save()

        return self


def upload_avi(instance: 'Profile', filename: str):
    return f'dy/accounts/{instance.user.pk}/{instance.pk}/{filename}'


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    main = models.BooleanField(default=False)
    minor = models.BooleanField(default=False)
    avi = models.ImageField(upload_to=upload_avi, default='/defaults/default_profile.jpg')
    objects = models.Manager()

    @property
    def tier(self):
        if self.user.tier == 'S':
            return SINGLE
        elif self.user.tier == 'F':
            return FAMILY

    @property
    def email(self):
        return self.user.email

    def delete(self, *args, **kwargs):
        if self.main:
            raise ValidationError(__('Main profile cannot be deleted'))

        return super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.clean()
        return super().save()

    def clean(self):
        profile_count = self.user.profile_set.count()

        if not self.pk and self.user.tier == 'S' and profile_count > 0:
                raise ValidationError(__('Maximum possible profiles (Upgradable)'))

        if not self.pk and self.user.main_profile and self.main:
            raise ValidationError(__('A main profile already exists'))

        elif not self.pk and self.user.tier == 'F' and profile_count > 5:
            raise ValidationError(__('Maximum possible profiles'))

        return super().clean()

    def __str__(self):
        return f'{self.name}(profile from {self.user.email})'

staff/models.py
from django.db import models
from django.utils.text import slugify


class HelpArticle(models.Model):
    title = models.CharField(max_length=1000)
    slug = models.SlugField(blank=True, null=True)
    description = models.CharField(max_length=2000)
    help_text = models.TextField()
    is_staff = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return f'HelpArticle: {self.title}'

    def save(self, *args, **kwargs):
        pk = self.pk
        super().save()

        if not pk or not self.slug:
            self.slug = f'{slugify(self.title)}-{self.pk}'
            self.save()

staff/forms.py
from typing import Union, List

from django.utils import timezone
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as __

from .models import HelpArticle
from .widgets import MarkdownEditor
from .logs_processing import log_action_ids, staff_logs, Log


def get_action_choices():
    choices = [(
        val,
        val.translate(str.maketrans('_', ' ')).capitalize()
    ) for val in log_action_ids.__dict__.values()]
    choices.insert(0, ('', '-Select action-'))
    return tuple(choices)


class HelpArticleForm(forms.ModelForm):

    class Meta:
        model = HelpArticle
        exclude = ('slug',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'help_text': MarkdownEditor()
        }


class HelpArticleEditForm(forms.ModelForm):

    class Meta:
        model = HelpArticle
        fields = ('description', 'help_text')
        widgets = {
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'help_text': MarkdownEditor()
        }


class LogSearchForm(forms.Form):
    to = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Action happened to?'}),
        help_text='The user the action happened to',
        required=False
    )
    by = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Action was done by?'}),
        help_text='The user that did the action',
        required=False
    )
    user = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Action happened to or was by whom?'}),
        help_text='Logs that involve the user, This ignores by and to/includes both',
        required=False
    )
    action = forms.ChoiceField(
        choices=get_action_choices(),
        help_text='Action performed; Choose one',
        required=False,
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    start_time = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget(
        attrs={'class': 'form-control'},
        date_format='dd/mm/yyyy',
        time_format='hh:mm',
        date_attrs={
            'type': 'date',
        },
        time_attrs={
            'type': 'time',
        }
    ), required=False, help_text='Filter logs from when')
    end_time = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget(
        date_format='dd/mm/yyyy',
        time_format='hh:mm',
        date_attrs={
            'type': 'date',
        },
        time_attrs={
            'type': 'time',
        }
    ), required=False, help_text='Filter logs up to')

    def clean_end_time(self):
        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')

        if type(start_time) == timezone.datetime and type(end_time) == timezone.datetime:
            if start_time > end_time:
                raise ValidationError(__('Start time cannot be more recent compared to end time.'))

        return end_time

    def get_logs(self) -> Union[List[Log], List]:
        logs = []
        if self.cleaned_data and type(self.cleaned_data) == dict:
            s_data = {
                key: value for key, value in zip(self.cleaned_data.keys(), self.cleaned_data.values()) if value
            }
            logs = staff_logs.search(**s_data)
        return logs

staff/templates/staff/add_user.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block title %}Add User{% endblock title %}

{% block staff %}active{% endblock staff %}

{% block style %}<link type="text/css" rel="stylesheet" href="{% static 'staff/css/add_user.css' %}">{% endblock style %}

{% block content %}

    <div class="container">
        {% if manage %}
            {% if manage.is_superuser %}
                <div class="row">
                    <div class="col-md-6">
                        {% include 'staff/user_details.html' with d_user=manage %}
                    </div>
                    <div class="col-md-3">
                        <h2>This user cannot be managed.</h2>
                    </div>
                </div>
            {% else %}
                <div class="row">
                    <div class="col-md-4" id="ud">
                        {% include 'staff/user_details.html' with d_user=manage %}
                        <hr>

                        {% if manage.is_staff %}
                            <form action="{% url 'staff:add-users' %}" method="post" class="skimmy-border">
                                {% csrf_token %}
                                <h4>'{{ manage.username }}' is staff, change this</h4>
                                <div class="alert alert-danger">By clicking the button below, '{{ manage.username }}' will no longer be a staff member, They will lose all thier access.<br />Are you sure?</div>
                                <input type="hidden" value="{{ manage.email }}" name="email">
                                <input type="hidden" value="1" name="remove-staff" />
                                <div class="form-group">
                                    <input type="submit" value="remove '{{ manage.username }}' from staff" class="btn btn-outline-danger">
                                </div>
                            </form>
                        {% endif %}

                    </div>

                    {% if not manage.is_staff %}
                        <div class="col-md-4">
                            <form action="{% url 'staff:add-users' %}" method="post">
                                {% csrf_token %}
                                <h4>To manage the user, they have to be staff</h4>
                                <div class="alert alert-info">By clicking the button below, you make '{{ manage.username }}' a staff member who has access to this site.<br />Are you sure?</div>
                                <input type="hidden" value="{{ manage.email }}" name="email">
                                <input type="hidden" value="1" name="make-staff" />
                                <div class="form-group">
                                    <input type="submit" value="Make '{{ manage.username }}' staff">
                                </div>
                            </form>
                        </div>
                    {% else %}
                        <div class="col-md-8">
                            <h4>Add or remove '<a href="{% url 'staff:staff-view' %}?staff-id={{ manage.pk }}">{{ manage.username }}</a>' from any of the following groups.</h4>

                            <div id="group-grp" class="skimmy-border">
                                <ul id="nav-tabs-sec" class="nav nav-tabs">
                                    {% for group in groups %}
                                        <li class="nav-item">
                                            <span class="nav-link tab-nav{% if forloop.counter == 1 %} active{% endif %}" href="#" data-section-to="group-{{ group.pk }}" data-section-from="" id="group-{{ group.pk }}-open">{{ group.name }}</span>
                                        </li>
                                    {% endfor %}
                                </ul>

                                {% for group in groups %}
                                    <div id="group-{{ group.pk }}" class="group-tab{% if forloop.counter == 1 %} group-tab-active{% endif %}">
                                        {% if group in manage.groups.all %}
                                            <form action="{% url 'staff:add-users' %}" method="post">
                                                {% csrf_token %}
                                                <h4>Remove "{{ manage.username }}" from <a href="{% url 'staff:staff-groups' %}?group-id={{ group.pk }}" target="_blank" rel="noopener noreferrer">{{ group.name }}</a> </h4>
                                                <div class="alert alert-warning">
                                                    By clicking the button below you strip "{{ manage.username }}" the following permissions;
                                                    <ul>
                                                        {% for perm in group.permissions.all %}
                                                            <li>{{ perm.name }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                                <input type="hidden" value="{{ manage.email }}" name="email">
                                                <input type="hidden" value="{{ group.pk }}" name="group-remove"/>
                                                <div class="form-group">
                                                    <input type="submit" value="remove '{{ manage.username }}' from {{ group.name }}" class="btn btn-outline-danger">
                                                </div>
                                            </form>
                                        {% else %}
                                            <form action="{% url 'staff:add-users' %}" method="post">
                                                {% csrf_token %}
                                                <h4>Add "{{ manage.username }}" to <a href="{% url 'staff:staff-groups' %}?group-id={{ group.pk }}" target="_blank" rel="noopener noreferrer">{{ group.name }}</a> </h4>
                                                <div class="alert alert-info">
                                                    By clicking the button below you give "{{ manage.username }}" the following permissions;
                                                    <ul>
                                                        {% for perm in group.permissions.all %}
                                                            <li>{{ perm.name }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                                <input type="hidden" value="{{ manage.email }}" name="email">
                                                <input type="hidden" value="{{ group.pk }}" name="group-add"/>
                                                <div class="form-group">
                                                    <input type="submit" value="Add '{{ manage.username }}' to {{ group.name }}">
                                                </div>
                                            </form>
                                        {% endif %}
                                        <span>To learn more about "{{ group.name }}", <a href="{% url 'staff:help-list' %}?q=staff groups">follow this link</a></span>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                    {% endif %}
                </div>
            {% endif %}
        {% else %}
            <div id="search-email">
                <form action="{% url 'staff:add-users' %}" method="post">
                    {% csrf_token %}
                    {% if email_not_found %}
                        <div class="alert alert-warning">
                            The email you entered does not exist on tyne music
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <label for="email">Enter the email of the user you want to manage</label>
                        <input type="email" name="email" id="email" class="form-control" required value="{{ email }}" placeholder="Enter email to manage a user">
                    </div>
                    <div class="form-group">
                        <input type="submit" value="get user" class="btn btn-outline-dark">
                    </div>
                </form>
            </div>
        {% endif %}
    </div>

{% endblock content %}

{% block bottomScript %}
<script src="{% static '/staff/js/tabMaster.js' %}"></script>
{% endblock bottomScript %}

staff/templates/staff/groups.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block title %}{% if group_id %}{{ group.name }}{% else %}Groups{% endif %}{% endblock title %}

{% block staff %}active{% endblock staff %}

{% block style %} <link rel="stylesheet" href="{% static 'staff/css/groups.css' %}" type="text/css"> {% endblock style %}

{% block content %}

{% if group_id %}
    <div class="container">
        <div class="group-home row">
            <div class="groups-all col-md-2">
                <a href="{% url 'staff:staff-groups' %}" class="btn btn-outline-dark">Groups</a>
                {% for x_group in groups %}
                <div class='ot-grp'>
                    <a href="{% url 'staff:staff-groups' %}?group-id={{ x_group.pk }}">{{ x_group.name }}</a>
                </div>
                {% endfor %}
            </div>

            <div class="col-md-1"></div>

            <div class="group-info col-md-4 alert alert-info">
                <h4>{{ group.name }}</h4>
                <p>Members: {{ group.user_set.count }}</p>

                <ul>
                    {% for member in group.user_set.all %}
                        <li>
                            <a href="{% url 'staff:staff-view' %}?staff-id={{ member.pk }}">{{ member.username }}</a><br />
                            {{ member.email }}
                        </li>
                    {% empty %}
                    <span>No members.</span>
                    {% endfor %}
                </ul>
            </div>

            <div class="col-md-1"></div>

            <div class="col-md-4 alert alert-info">
                Permission users in '{{ group.name }}' have ({{ group.permissions.count }});

                <ul>
                    {% for permission in group.permissions.all %}
                        <li>{{ permission.name }}</li>
                    {% empty %}
                        <p>No permissions</p>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% else %}
    {% if groups %}
        <h2 class="text-center">Groups available</h2>
        <div class="groups">
            {% for l_group in groups %}
                <div class="group skimmy-border row">
                    <div class="col-md-8 group-text">
                        <h4>{{ l_group.name }}</h4>
                        <p>Members: {{ l_group.user_set.count }}</p>
                    </div>
                    <a href="{% url 'staff:staff-groups' %}?group-id={{ l_group.pk }}" class="col-md-4 forw-arrow-grp-home">
                        <svg class="forw-arrow-grp" xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48"><path d="M24 8l-2.83 2.83L32.34 22H8v4h24.34L21.17 37.17 24 40l16-16z"/></svg>
                    </a>
                </div>
            {% endfor %}        
        </div>
    {% else %}
        <h2>No groups available</h2>
    {% endif %}
{% endif %}


{% endblock content %}

staff/templates/staff/help_detail.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block title %}Help{% endblock title %}

{% block help %}active{% endblock help %}

{% block style %}<link type="text/css" rel="stylesheet" href="{% static 'staff/css/help_detail.css' %}" />{% endblock style %}


{% block content %}
    <div class="container">
        <h1>{{ article.title }}</h1>

        <p>This article tries to explain:</p>
        <p>{{ article.description }}</p>
        <hr>
        <p id="help-article">
            <nav class="navbar sticky-top navbar-dark bg-dark" id="article-sections-nav">
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        <strong>{{ article.title }} sections</strong>
                    </a>
            
                    <ul id="article-nav-drop-down" class="dropdown-menu" aria-labelledby="dropdownMenuLink">Loading...</ul>
                </div>

                <span class="navbar-text">
                    {% if perms.staff.change_helparticle and perms.staff.delete_helparticle %}
                        <a href="{% url 'staff:help-edit' article.pk %}"><button class="btn btn-outline-primary">Edit '{{ article.title }}'</button></a>
                        <span style="width: 10px;"></span>
                        <a href="{% url 'staff:help-delete' article.pk %}"><button class="btn btn-outline-danger">Delete '{{ article.title }}'</button></a>
                        <button style="visibility: hidden;" class="btn btn-outline-danger">Delete '{{ article.title }}'</button>
                    {% endif %}
                </span>
            </nav>
            
            <div id="article-top" class="js-article">
                <div class="text-center">
                    <img src="{% static 'imgs/200.gif' %}">
                </div>
                <input type="hidden" id="js-article-content" value="{{ article.help_text }}">
            </div>
        </p>
    </div>

{% endblock content %}

{% block bottomScript %}
<script src="{% static 'staff/js/marked.min.js' %}"></script>
<script src="{% static 'staff/js/articleSection.js' %}"></script>
<script src="{% static 'staff/js/article.js' %}"></script>
{% endblock bottomScript %}

staff/templates/staff/help_list.html
{% extends 'staff/staff_base.html' %}
{% load static %}

{% block title %}Help{% endblock title %}

{% block help %}active{% endblock help %}

{% block style %}<link type="text/css" rel="stylesheet" href="{% static 'staff/css/help_list.css' %}" />{% endblock style %}

{% block content %}
    <div class="container">
        {% if articles %}
            <h3>Staff Help Articles</h3>
            <hr>

            <div id="articles">
                {% for article in articles %}
                    <div class="article">
                        <h5><a href="{% url 'staff:help-article' article.pk %}">{{ article.title }}</a></h5>
                        <p>{{ article.description }}</p>
                        <small>Last modified {{ article.modified }}</small>
                        <hr>
                        {% if perms.staff.change_helparticle and perms.staff.delete_helparticle %}
                            <div class="row">
                                <div class="col-md-2">
                                    <a href="{% url 'staff:help-edit' article.pk %}" class="btn btn-outline-dark">Edit '{{ article.title }}'</a>
                                </div>
                                <div class="col-md-1"></div>
                                <div class="col-md-2">
                                    <a href="{% url 'staff:help-delete' article.pk %}" class="btn btn-outline-danger">Delete '{{ article.title }}'</a>
                                </div>
                            </div>
                            <hr>
                        {% endif %}
                    </div>
                {% endfor %}

            </div>
        {% else %}
            <h3>No help articles available</h3>
        {% endif %}

    </div>


{% endblock content %}

staff/templates/staff/staff_roles_list.html
<h2>Staff Members</h2>

<div class="row">
    {% for staff_member in staff %}
        <div class="staff-member col-md-3 skimmy-border">
            <div class="details">
                <p>username: <strong>{{ staff_member.username }}</strong>{% if staff_member.pk == user.pk %} (You){% endif %}</p>
                <p>email: <strong>{{ staff_member.email }}</strong></p>
            </div>
            <div class="row add-info">
                <div class="col-sm">
                    <a href="{% url 'staff:staff-view' %}?staff-id={{ staff_member.pk }}" class="btn btn-outline-dark">Details</a>
                </div>

                {% if user.pk != staff_member.pk and not staff_member.is_superuser %}
                    <div class="col-sm">
                        <form action="{% url 'staff:add-users' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="email" value="{{ staff_member.email }}">
                            <button class="btn btn-outline-dark">Manage</button>
                        </form>
                    </div>
                {% endif %}
                {% if user.is_superuser %}
                    <div class="col-sm">
                        <a href="{% url 'staff:logs' %}?by={{ staff_member.username }}({{ staff_member.pk }})" class="btn btn-outline-dark">view activity</a>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>