core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    # accounts/create/ or accounts/edit/ or accounts/get/?username=user
    path('accounts/<str:action>/', views.account_action, name='account-action'),

    # login/
    path('login/', views.login, name='login'),

    # profile/create/
    path('profile/create/', views.profile_create, name='profile-create'),

    # profile/edit/1/
    path('profile/edit/<int:profile_pk>/', views.profile_edit, name='profile-edit'),

    # profile/delete/1/
    path('profile/delete/<int:profile_pk>/', views.profile_delete, name='profile-delete'),
]

staff/urls.py
from django.urls import path

from . import views


app_name = 'staff'

urlpatterns = [
    # /
    path('', views.StaffHome.as_view(), name='home'),

    # /add_user_to_staff/
    path('manage-staff-user/', views.AddAdminUsers.as_view(), name='add-users'),

    # staff-roles/
    path('staff-roles/', views.StaffRolesView.as_view(), name='staff-view'),

    # staff-groups/
    path('staff-groups/', views.GroupInfoView.as_view(), name='staff-groups'),

    # help/
    path('help/', views.StaffHelpList.as_view(), name='help-list'),

    # help/article/how-to-use-staff-page/
    path('help/article/<int:article_pk>/', views.StaffHelpArticlePage.as_view(), name='help-article'),

    # help/manage/
    path('help/manage/', views.StaffArticleAdd.as_view(), name='help-add'),

    # help/manage/edit/43/
    path('help/manage/edit/<int:article_pk>/', views.StaffArticleEdit.as_view(), name='help-edit'),

    # help/manage/delete/43/
    path('help/manage/delete/<int:article_pk>/', views.StaffArticleHelpDelete.as_view(), name='help-delete'),

    # logs/
    path('staff-activity/', views.StaffLogs.as_view(), name='logs'),

    # search-artists/
    path('search-artists/', views.artists_names, name='search-artists'),

    # manage-albums/
    path('manage-albums/', views.StaffAlbumView.as_view(), name='manage-albums'),

    # manage-albums/published-status/23/
    path('manage-albums/published-status/<int:album_pk>/', views.PublishAlbums.as_view(), name='album-publish-status'),

    # manage-albums/edit/23/
    path('manage-albums/edit/<int:album_pk>/', views.AlbumEditView.as_view(), name='album-edit'),

    # manage-albums/delete/23/
    path('manage-albums/delete/<int:album_pk>/', views.AlbumDelete.as_view(), name='album-delete'),

    # manage-albums/create/
    path('manage-albums/create/', views.StaffAlbumCreateView.as_view(), name='album-create'),

    # manage-albums/disc/new/23/
    path('manage-albums/disc/new/<int:album_id>/', views.add_disc_to_album, name='new-disc'),

    # manage-albums/disc/change/34/
    path('manage-albums/disc/change/<int:disc_id>/', views.change_disc_name, name='change-disc'),

    # manage-albums/disc/delete/34/
    path('manage-albums/disc/delete/<int:disc_id>/', views.delete_disc_from_album, name='delete-disc'),

    # manage-albums/disc/34/song/new/
    path('manage-albums/disc/<int:disc_id>/song/new/', views.CreateSongView.as_view(), name='new-song'),

    # manage-albums/song/14/edit/
    path('manage-albums/song/<int:song_id>/edit/', views.EditSongView.as_view(), name='edit-song'),

    # manage-albums/song/14/delete/
    path('manage-albums/song/<int:song_id>/delete/', views.DeleteSongView.as_view(), name='delete-song'),

    # manage-artists/
    path('manage-artists/', views.StaffArtistsView.as_view(), name='manage-artists'),

    # manage-artists/edit/49/members/
    path('manage-artists/edit/<int:artist_id>/members/', views.EditArtistGroupMember.as_view(), name='group-members'),

    # manage-artists/edit/49/
    path('manage-artists/edit/<int:artist_id>/', views.EditArtist.as_view(), name='artist-edit'),

    # manage-artists/create/
    path('manage-artists/create/', views.ArtistCreate.as_view(), name='artist-create'),

    # manage-artists/delete/23/
    path('manage-artists/delete/<int:artist_id>/', views.ArtistDelete.as_view(), name='artist-delete'),

    # manage-creators/
    path('manage-creators/', views.CreatorsHomeView.as_view(), name='manage-creators'),

    # manage-creators/creator/22/
    path('manage-creators/creator/<int:creator_id>/', views.CreatorDetailView.as_view(), name='creator-detail'),

    # manage-creators/creator/22/edit-genres*/
    path(
        'manage-creators/creator/<int:creator_id>/<str:action>/',
        views.CreatorDetailActions.as_view(),
        name='creator-actions'
    ),

    # manage-creators/creator/delete/22/
    path('manage-creators/creator/delete/<int:creator_id>/', views.CreatorDeleteView.as_view(), name='creator-delete'),

    # manage-creators/creator/edit/22/
    path('manage-creators/creator/edit/<int:creator_id>/', views.CreatorUpdateView.as_view(), name='creator-edit'),

    # manage-creators/creator/new/
    path('manage-creators/create/', views.CreatorNewView.as_view(), name='creator-create'),

]

tyne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls

from core.views import master_login, master_logout, TempHomePage, master_signup

docs_description = """
    This are the API end points available on tyne music
"""

urlpatterns = [
    # /
    path('', TempHomePage.as_view(), name='home'),

    # admin/
    path('admin/', admin.site.urls),

    # core/
    path('core/', include('core.urls')),

    # music/
    path('music/', include('music.urls')),

    # staff/
    path('staff/', include('staff.urls')),

    # login/
    path('login/', master_login, name='master-login'),

    # logout/
    path('logout/', master_logout, name='master-logout'),

    # signup/
    path('signup/', master_signup, name='master-signup'),

    # docs/
    path('docs/', include_docs_urls(title='Tyne Music API docs', description=docs_description))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from itertools import chain

from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as __
from django.core.exceptions import ValidationError

from core.models import Profile


def upload_artist_image(instance: 'Artist', filename: str, cover: bool = False):
    inter_type = instance.pk if instance.pk else 'new'
    if cover:
        inter_type = f'{inter_type}/covers'
    else:
        inter_type = f'{inter_type}/avis'

    return f'dy/music/artists/{inter_type}/{filename}'


# upload_artist_cover = lambda instance, filename: upload_artist_image(instance, filename, True)
def upload_artist_cover(instance: 'Artist', filename: 'str'):
    upload_artist_image(instance, filename, True)


def upload_creator_image(instance: 'Creator', filename: str):
    return f'dy/music/creators/creators/{instance.pk if instance.pk else "new"}/{filename}'


def upload_genre_image(instance: 'Genre', filename: str):
    return f'dy/music/creators/genres/{instance.pk if instance.pk else "new"}/{filename}'


def upload_album_image(instance: 'Album', filename: str):
    inter_type = f'{instance.pk}/cover' if instance.pk else "new"
    return f'dy/music/albums/{inter_type}/{filename}'


def upload_song_file(instance: 'Song', filename: str):
    return f'dy/music/albums/{instance.disc.album.pk}/disks/{instance.disc.pk}/{filename}'


def upload_playlist_image(instance: 'Playlist', filename: str):
    inter_type = instance.pk if instance.pk else "new"
    if instance.profile:
        abs_path = f'users/{instance.profile.user.pk}/{instance.profile.pk}/{inter_type}/{filename}'
    elif instance.creator:
        abs_path = f'creator/{instance.creator.pk}/{inter_type}/{filename}'
    else:
        abs_path = f'blank/{inter_type}/{filename}'

    return f'dy/music/playlists/{abs_path}'


class Artist(models.Model):
    name = models.CharField(max_length=100, help_text='Artist\'s name')
    is_group = models.BooleanField(default=False, help_text='Is the artist a group')
    group_members = models.ManyToManyField('self', blank=True)
    bio = models.TextField(blank=True, null=True, help_text='Info about the artist')
    nicknames = models.TextField(blank=True, null=True, help_text='Comma separated names the artist goes by')
    playlists = models.ManyToManyField('Playlist', blank=True)
    objects = models.Manager()
    avi = models.ImageField(
        default='/defaults/artist.png',
        upload_to=upload_artist_image,
        help_text='A 1x1 image'
    )
    cover = models.ImageField(
        default='/defaults/artist_large.png',
        upload_to=upload_artist_cover,
        help_text='A 3x1 image'
    )

    def add_artist_to_group(self, artist: 'Artist'):
        if self.is_group and type(artist) == type(self) and not artist.is_group:
            self.group_members.add(artist)

    def all_nicknames(self):
        return [name.strip() for name in self.nicknames.split(',')]

    def a_type(self):
        return 'Group' if self.is_group else 'Artist'

    def __repr__(self):
        return f'<{self.a_type()} \'{self.name}\'>'

    def __str__(self):
        return f'{self.name} ({self.a_type()})'


class Genre(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    avi = models.ImageField(default='/defaults/genre.png', upload_to=upload_genre_image)
    cover = models.ImageField(default='/defaults/genre_wide.png', upload_to=upload_genre_image)
    main_curator = models.ForeignKey('Creator', blank=True, null=True, on_delete=models.PROTECT)
    objects = models.Manager()

    def __str__(self):
        return f'{self.title} (genre)'

    def __repr__(self):
        return f'<Genre: \'{self.title}\'>'


class Creator(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    avi = models.ImageField(default='/defaults/creator.png', upload_to=upload_creator_image)
    cover = models.ImageField(default='/defaults/creator_wide.png', upload_to=upload_creator_image)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    genres = models.ManyToManyField(Genre, blank=True)
    objects = models.Manager()

    def add_creator_user(self, user):
        perms_for_curator = [
            'music.view_creator', 'music.change_creator', 'music.delete_creator',
            'music.view_creatorsection', 'music.change_creatorsection', 'music.add_creatorsection',
            'music.delete_creatorsection'
        ]
        if hasattr(user, 'is_staff') and user.is_staff and user.has_perms(perms_for_curator):
            self.users.add(user)

    def __str__(self):
        return f'{self.name} (curator)'

    def __repr__(self):
        return f'<TyneMusicContentCreator: \'{self.name}\'>'


class Disc(models.Model):
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True, null=True)
    objects = models.Manager()

    def __str__(self):
        return f'{self.name if self.name else "Disc"} from \'{self.album}\''


class Album(models.Model):
    title = models.CharField(max_length=200)
    notes = models.TextField(blank=True, null=True)
    genre = models.ForeignKey(Genre, on_delete=models.PROTECT)
    date_of_release = models.DateField()
    is_single = models.BooleanField(default=False)
    is_ep = models.BooleanField(default=False)
    cover = models.ImageField(default='/defaults/album.png', upload_to=upload_album_image)
    likes = models.IntegerField(default=0, null=True, blank=True)
    copyright = models.TextField(blank=True, null=True)
    artists = models.ManyToManyField(Artist, blank=True)
    other_versions = models.ManyToManyField('self', blank=True)
    published = models.BooleanField(default=False)
    objects = models.Manager()

    @property
    def album_type(self):
        return {
            'LP': 'Long Play',
            'EP': 'Extended Play',
            'S': 'Single'
        }.get(self.al_code(), 'UNKNOWN')

    @property
    def disc_one(self):
        if self.pk and self.disc_set.count() > 0:
            return self.disc_set.all()[0]

    def al_code(self):
        t = 'LP'
        if self.is_ep:
            t = 'EP'
        elif self.is_single:
            t = 'S'
        return t

    def all_songs(self):
        if self.pk:
            return Song.objects.filter(disc__album__pk=self.pk)

    def add_sister_album(self, album):
        if type(album) == type(self) and self.pk:
            for other_version in self.other_versions.all():
                other_version.other_versions.add(album)
            self.other_versions.add(album)

    def clean(self):
        if self.is_single and self.is_ep:
            raise ValidationError(__('EP or Single not both'))

        return super().clean()

    def save(self, *args, **kwargs):
        self.clean()
        pk = self.pk
        super().save(*args, **kwargs)
        if not pk:
            return Disc.objects.create(
                name='Disc 1',
                album=self
            )

    def delete(self, using=None, keep_parents=False):
        if self.cover != '/defaults/album.png':
            self.cover.delete()

        return super().delete(using, keep_parents)

    def __repr__(self):
        name = 'Album'
        if self.is_ep:
            name = 'EP'
        elif self.is_single:
            name = 'Single'

        return f'<{name}: \'{self.title}\'>'

    def __str__(self):
        return f'{self.title} ({self.date_of_release})'


class Song(models.Model):
    disc = models.ForeignKey(Disc, on_delete=models.CASCADE, blank=False, null=False)
    track_no = models.IntegerField()
    title = models.CharField(max_length=200)
    genre = models.ForeignKey(Genre, on_delete=models.PROTECT)
    explicit = models.BooleanField(default=False)
    length = models.IntegerField(default=0, help_text='Length of the song in seconds')
    file = models.FileField(blank=True, null=True, upload_to=upload_song_file)
    likes = models.IntegerField(default=0, blank=True, null=True)
    additional_artists = models.ManyToManyField(Artist, blank=True, related_name='additions')
    featured_artists = models.ManyToManyField(Artist, blank=True, related_name='features')
    streams = models.IntegerField(default=0, blank=True, null=True)
    objects = models.Manager()

    class Meta:
        unique_together = (('disc', 'track_no'),)
        ordering = ('track_no',)

    @property
    def album_art(self):
        return self.disc.album.cover.url

    @property
    def length_string(self):
        length = '0:00'
        if self.pk and self.length:
            minutes = self.length % 60
            minutes_ = minutes if minutes > 9 else f'0{minutes}'
            length = f'{self.length // 60}:{minutes_}'
        return length

    @property
    def album_artists(self):
        return self.disc.album.artists.all()

    def add_additional_artist(self, artist):
        if self.pk and type(artist) == Artist and artist not in self.disc.album.artists.all():
            self.additional_artists.add(artist)

    def add_featured_artist(self, artist):
        if self.pk and type(artist) == Artist and artist not in self.disc.album.artists.all():
            self.featured_artists.add(artist)

    def song_artists(self):
        artists = []

        if self.additional_artists.count() > 0:
            artists = chain(self.disc.album.artists.all(), self.additional_artists.all())

        return artists

    def __repr__(self):
        return f'<Song: \'{self.title}\' from \'{self.disc.album}\'>'

    def __str__(self):
        return f'\'{self.title}\' from the album \'{self.disc.album}\''


class Playlist(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    creator = models.ForeignKey(Creator, on_delete=models.CASCADE, blank=True, null=True)

staff/models.py
from django.db import models
from django.utils.text import slugify


class HelpArticle(models.Model):
    title = models.CharField(max_length=1000)
    slug = models.SlugField(blank=True, null=True)
    description = models.CharField(max_length=2000)
    help_text = models.TextField()
    is_staff = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return f'HelpArticle: {self.title}'

    def save(self, *args, **kwargs):
        pk = self.pk
        super().save()

        if not pk or not self.slug:
            self.slug = f'{slugify(self.title)}-{self.pk}'
            self.save()

staff/templates/staff/albums/album_confirm_delete.html
{% extends "staff/staff_base.html" %}

{% block title %}Delete '{{ album.title }}'{% endblock title %}
{% block help %}active{% endblock help %}

{% block content %}
    <div class="col-sm-9 container">
        <div>
            <h2>Are you sure you want to delete {{ album.title }}</h2>
            <p class="text-primary">
                once {{ album.title }} is deleted it cannot be recovered! <br/>
                Another solution would be to unpublish it
            </p>
            
            <div class="row">
                <div class="col-md-3">
                    {% if album.published %}
                        <form action="{% url 'staff:album-publish-status' album.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="un-publish" value="1">
                            <button type="submit" class="btn btn-outline-danger">Un publish '{{ album.title }}' instead</button>
                        </form>
                    {% endif %}
                </div>

                <div class="col-md-1"></div>

                <div class="col-md-4">
                    <form class="form-inline" method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-outline-danger" value="delete">
                        <a style="margin-left: 10px" href="{% url 'staff:manage-albums' %}?album-id={{ album.pk }}" class="btn btn-outline-primary">cancel</a>                     
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

staff/templates/staff/albums/albums.html
{% extends 'staff/staff_base.html' %}
{% load static %}
{% load music_filter %}

{% block title %}Manage {% if album %}{{ album }}{% else %}albums{% endif %}{% endblock title %}

{% block staff %}active{% endblock staff %}

{% block search_action %}{% url 'staff:manage-albums' %}{% endblock search_action %}

{% block search_placeholder %}album by title or artists{% endblock search_placeholder %}

{% block style %}{% if album_id %}<link rel="stylesheet" href="{% static 'staff/css/albums/album_info.css' %}" type="text/css">{% else %}<link rel="stylesheet" href="{% static 'staff/css/albums/albums.css' %}" type="text/css">{% endif %}{% endblock style %}

{% block content %}


    {% if album_id %}
    {% comment %} Single Album {% endcomment %}

    <div class="container">
        <div class="row">

            <div class="col-md-4">
                <div class="alert alert-info">
                    <img src="{{ album.cover.url }}" alt="{{ album.title }}'s cover" class="album-info-cover-img">
                    <h2>{{ album.title }} ({{ album.date_of_release.year }})</h2>
                    <h5>by {% for artist in album.artists.all %}{% if forloop.counter > 1 %}, {% endif %} <a href="" target="_blank" rel="noopener noreferrer">{{ artist.name }}</a>{% endfor %} </h5>
                    <p>Released <strong>{{ album.date_of_release|full_release }} ({{ album.date_of_release|release_date_to }})</strong></p>
                    <hr>
                    <ul class="list-unstyled">
                        <li>Album Type: <strong>{{ album.album_type }}</strong></li>
                        <li>Artists Display Name: <strong>{{ album.artists|album_artists }}</strong></li>
                        <li>Genre: <strong>{{ album.genre.title }}</strong></li>
                        <li>Likes: <strong>{{ album.likes }}</strong></li>
                        <li>Copyright: <pre>{{ album.copyright }}</pre></li>
                    </ul>
                    <a href="{% url 'staff:manage-albums' %}" class="btn btn-outline-dark">All albums</a>
                    <a href="{% url 'staff:album-edit' album.pk %}" class="btn btn-outline-secondary">Edit '{{ album.title }}'</a>
                </div>

                {% if album.published %}
                    <div class="alert alert-danger text-center">
                        <h4>"{{ album.title }}" is  published</h4>
                        <form action="{% url 'staff:album-publish-status' album.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="un-publish" value="1">
                            <button type="submit" class="btn btn-outline-danger">Un publish '{{ album.title }}'</button>
                        </form>
                    </div>
                    {% else %}
                    <div class="alert alert-primary text-center">
                        <h4>"{{ album.title }}" is <strong>NOT</strong> published</h4>
                        <form action="{% url 'staff:album-publish-status' album.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="publish" value="1">
                            <button type="submit" class="btn btn-outline-danger">Publish '{{ album.title }}'</button>
                        </form>
                    </div>
                {% endif %}
                <div class="alert alert-danger text-center">
                    <h4>Once "{{ album.title }}" is deleted it can not be recovered.</h4>
                        <a href="{% url 'staff:album-delete' album_pk=album.pk %}" class="btn btn-outline-danger">Delete '{{ album.title }}'</a>
                </div>
            </div>

            <div class="col-md-8 songs">
                {% if album.notes %}
                    <pre class="alert alert-info notes">{{ album.notes }}</pre>
                    <hr>
                {% endif %}
                <div>
                    {% for disc in album.disc_set.all %}
                        <h4 id="disc-{{ disc.pk }}">{{ disc.name }}</h4>
                        <ul class="list-unstyled">
                            {% for song in disc.song_set.all %}
                                <li class="song row">
                                    <span class="col-md-1">{{ song.track_no }}.</span>
                                    <a href="{% url 'staff:edit-song' song_id=song.pk %}" class="col-md-6">{{ song.title }}</a>
                                    <span class="col-md-2">{{ song.length_string }}</span>
                                    {% if song.additional_artists.count > 0 %}
                                        <span class="col-md-3">{{ song.song_artists|album_artists:0 }}</span>
                                    {% else %}
                                        <span class="col-md-3">{{ song.genre.title }}</span>
                                    {% endif %}
                                </li>
                            {% empty %}
                                <h5>No songs available on "{{ disc.name }}"</h5>
                                {% if album.disc_set.count > 1 %}
                                    <form action="{% url 'staff:delete-disc' disc_id=disc.pk %}" method="post">
                                        {% csrf_token %}
                                        <input type="submit" value='Delete "{{ disc.name }}"' class="btn btn-outline-danger">
                                    </form>
                                {% endif %}
                            {% endfor %}
                        </ul>
                        <a href="{% url 'staff:new-song' disc_id=disc.pk %}" class="btn btn-outline-primary">Add song to {{ disc.name }}</a>
                        <button data-name-form-id="{{ disc.pk }}-name-form" class="btn btn-outline-secondary chg-disc-name">Change "{{ disc.name }}" name </button>

                        <form data-open="0" action="{% url 'staff:change-disc' disc_id=disc.pk %}" method="post" id="{{ disc.pk }}-name-form" class="col-md-6 disc-name-form alert alert-info">
                            {% csrf_token %}
                            <label for="disc-name-add">Disc name</label>
                            <input id="disc-name-add" type="text" name="disc-name" class="form-control" placeholder="Enter new disc name for '{{ disc.name }}'" required>
                            <hr>
                            <input type="submit" value="save new name" class="btn btn-outline-dark">
                        </form>
                        <hr>
                    {% endfor %}

                    <hr>

                    <form action="{% url 'staff:new-disc' album_id=album.pk %}" method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-outline-dark" value="Add disc to {{ album.title }}">
                    </form>
                </div>
            </div>

        </div>
    </div>

    {% else %}
    {% comment %} All albums {% endcomment %}
        <div class="container">
            {% if albums %}
                <div class="row top-links">
                    <h4 class="col-md-2">
                        {% if album_type == 'LP' %}Albums{% else %}{% if album_type == 'S' %}Singles{% else %}{% if album_type == 'EP' %}Extended Plays{% else %}All Records{% endif %}{% endif %}{% endif %} available
                    </h4>
                    <div class="col-md-2">
                        <a href="{% url 'staff:album-create' %}" class="btn btn-outline-primary">New Album</a>
                    </div>

                    <div class="col-md-2">
                        <a href="{% url 'staff:manage-albums' %}?t=S" class="btn btn-{% if album_type != 'S' %}outline-{% endif %}dark">Singles</a>
                    </div>

                    <div class="col-md-2">
                        <a href="{% url 'staff:manage-albums' %}?t=EP" class="btn btn-{% if album_type != 'EP' %}outline-{% endif %}dark">EPs</a>
                    </div>

                    <div class="col-md-2">
                        <a href="{% url 'staff:manage-albums' %}?t=LP" class="btn btn-{% if album_type != 'LP' %}outline-{% endif %}dark">Albums</a>
                    </div>
                    
                    {% if album_type or q %}
                    <div class="col-md-2">
                        <a href="{% url 'staff:manage-albums' %}" class="btn btn-outline-primary">All</a>
                    </div>
                    {% endif %}
                </div>
                <script type="text/javascript">
                    function clickLink(linkId) {
                        document.getElementById(linkId).click()
                    }
                </script>
                <div class="row">
                    {% for l_album in albums %}
                        <div class="album col-md-2">
                            <div class="album-info">
                                <h5 class="album-title" data-bs-toggle="tooltip" title="{{ l_album.title }} • {{ l_album.date_of_release.year }}">{{ l_album.title }}</h5>
                                <p class="album-description" {% if l_album.artists.count > 4 %}data-bs-toggle="tooltip" title="{{ l_album.artists|album_artists_string }}"{% endif %}>
                                    from {{ l_album.artists|album_artists }}
                                    |
                                    <strong>{{ l_album.date_of_release.year }}</strong>
                                </p>
                            </div>
                            <div class="album-link" onclick="clickLink('{{ l_album.pk }}-link')" aria-label="manage {{ l_album.title }}">
                                <a id="{{ l_album.pk }}-link" href="{% url 'staff:manage-albums' %}?album-id={{ l_album.pk }}">manage</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="text-center">
                    <h2>no albums available</h2>
                    <a href="" class="btn btn-outline-dark">Add New</a>
                    <a href="{% url 'staff:manage-albums' %}" class="btn btn-outline-primary">All albums</a>
                </div>
            {% endif %}
        </div>
    {% endif %}
{% endblock content %}


{% block bottomScript %}
    {% if album_id %}
        <script src="{% static 'staff/js/albums/album_info.js' %}"></script>
    {% endif %}
{% endblock bottomScript %}

staff/templates/staff/albums/create_album.html
{% extends 'staff/staff_base.html' %}
{% load static %}


{% block title %}New Album{% endblock title %}

{% block staff %}active{% endblock staff %}

{% block style %}
    {{ form.media.css }}
{% endblock style %}

{% block content %}

    <div class="container">
        <h2>Create a new album</h2>

        <form action="{% url 'staff:album-create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            {% include 'staff/albums/album_form.html' with initial_artists=force_artists %}

            <hr>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-dark">Save album</button>
            </div>
        </form>
    </div>

{% endblock content %}

{% block bottomScript %}
    {{ form.media.js }}
{% endblock bottomScript %}

staff/templates/staff/albums/edit_album.html
{% extends 'staff/staff_base.html' %}
{% load static %}
{% load music_filter %}


{% block title %}Edit '{{ form.instance.title }}'{% endblock title %}

{% block staff %}active{% endblock staff %}


{% block style %}
    {{ form.media.css }}
{% endblock style %}

{% block content %}
    <div class="container">
        <h2>Edit <a href="{% url 'staff:manage-albums' %}?album-id={{ form.instance.pk }}">{{ form.instance }}</a> by {{ form.instance.artists|album_artists }}</h2>
        {% if form.non_field_errors %}
            <div class="alert alert-warning">
                {% for error in form.non_field_errors %}
                    {{ error }} <br />
                {% endfor %}
            </div>
        {% endif %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'staff/albums/album_form.html' with initial_artists=album.artists %}
            <hr>
            <div class="form-group">
                <button class="btn btn-outline-dark">Edit album</button>
                <a href="{% url 'staff:manage-albums' %}?album-id={{ form.instance.pk }}" class="btn btn-outline-dark">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

{% block bottomScript %}
    {{ form.media.js }}
{% endblock bottomScript %}